DEFAULT_GLOBAL_CONFIG = {
    'usable_gpu': '3'
}

DEFAULT_OPENAI_APIKEY = '[YOUR_API KEY]'
DEFAULT_OPENAI_APIBASE = '[YOUR_API_BASE]'

DEFAULT_LLAMA3_8B_INSTRUCT_PATH = '[YOUR_PATH]'
DEFAULT_E5_BASE_V2_PATH = '[YOUR_PATH]'